stay in the grub2 menu across updates
We no longer want the boot menu entry to disappear after an explicit or
implicit `grub2-mkconfig`. To do this, we change the mechanism by which
the boot menu gets added:
1. The `bootentry` script adds/removes hooks inside the `/etc/grub.d/`
   directory. The hooks are positioned before and after the ostree hook.
   The `bootentry` script is now what the kickstart has to call (or what
   users must call if upgrading manually) in order to have the bootmenu
   added.
2. The `grub2_hook` script is run once before the ostree hook to find
   the latest BLS entry and create a new devmode entry based on that. It
   is also run once after the ostree hook to purge out the devmode
   entry. Otherwise on the next bootswap, ostree will read it in and
   create a new renamed entry in the future loader dir, so we wouldn't
   be able to recognize it and purge it.

This way, everytime the user does an upgrade/rebase/rollback, the
devmode entry is updated so that it uses the same tree as the new
default entry.

diff --git a/libexec/grub2_hook b/libexec/grub2_hook
--- a/libexec/grub2_hook
+++ b/libexec/grub2_hook
@@ -23,7 +23,10 @@
 set -euo pipefail
 IFS=$'\n\t'
 
-BLS_DIR="/boot/loader/entries/"
+# The BLS dir we operate on is the one that *will* become the new loader
+# symlink, not necessarily the current one.
+BLS_DIR="/boot/loader.${_OSTREE_GRUB2_BOOTVERSION}/entries/"
+
 DEVMODE_TITLE="Developer Mode"
 DEVMODE_NOCLOUD="/usr/share/atomic-devmode/cloud-init."
 
@@ -32,10 +35,21 @@ DEVMODE_NOCLOUD="/usr/share/atomic-devmode/cloud-init."
 
 main() {
 
+	# check which hook called us
+	if [[ $0 == *+ ]]; then
+		main_add_entry
+	elif [[ $0 == *- ]]; then
+		main_remove_entry
+	else
+		echo "ERROR: This script should not be called directly." >&2
+	fi
+}
+
+main_add_entry() {
+
 	# read in the most updated BLS entry
 	local entry_filename
 	entry_filename=$(get_bls_entry)
-	echo "INFO: Using BLS entry file \"$entry_filename\" as template."
 
 	local entry_text
 	entry_text=$(cat $entry_filename)
@@ -47,18 +61,18 @@ main() {
 	# save it back to disk
 	local new_entry_filename="${entry_filename%.conf}-devmode.conf"
 	echo "$new_entry_text" > "$new_entry_filename"
+}
 
-	# Generate a new grub config. NB: We manually override the bootversion for
-	# now because ostree versions before v2016.1 failed to detect the version
-	# properly (see https://github.com/GNOME/ostree/pull/165). We can probably
-	# drop this patch later on.
-	echo "INFO: Regenerating GRUB2 config"
-	local bootver; bootver=$(readlink /boot/loader)
-	_OSTREE_GRUB2_BOOTVERSION=${bootver#*.} \
-		grub2-mkconfig -o /boot/loader/grub.cfg
+main_remove_entry() {
 
-	# and now we can get rid of our file
-	rm "$new_entry_filename"
+	# make sure the directory exists and is writeable
+	if [ ! -w "$BLS_DIR" ]; then
+		echo "ERROR: Directory \"$BLS_DIR\" not writeable." >&2
+		exit 1
+	fi
+
+	# remove any leftover devmode BLS entries
+	find "$BLS_DIR" -name '*-devmode.conf' -delete
 }
 
 get_bls_entry() {
